//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repetido.Models.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bloqueo
    {
        public int Id_Bloqueo { get; set; }
        public int Id_Jugador { get; set; }
        public int Id_Bloqueado { get; set; }
    
        public virtual Jugador Jugador { get; set; }
        public virtual Jugador Jugador1 { get; set; }
    }
}
