//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repetido.Models.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partida
    {
        public int Id_Partida { get; set; }
        public string Tipo { get; set; }
        public int Id_Jugador1 { get; set; }
        public int Id_Jugador2 { get; set; }
        public int Id_Torneo { get; set; }
    
        public virtual Jugador Jugador { get; set; }
        public virtual Jugador Jugador1 { get; set; }
        public virtual Torneo Torneo { get; set; }
    }
}
